### ISSUE TITLE
Gnome 3.36?

### ISSUE THREAD

**Issue by vinliao** [tliron/install-gnome-themes#46]
~~Gnome 3.36 is not supported yet. I think adding one line on the script would fix this.~~

Oops, not as simple as I thought. Here's the issue I have.

```
Code/install-gnome-themes [master] » ./install-gnome-themes
Detected GNOME 3.36, GTK 3.24.
/home/vinliao/Code/install-gnome-themes/utils.sh: line 40: lsb_release: command not found
Detected Fedora operating system.
Adapta, Adapta-Eta, Adapta-Nokto, Adapta-Nokto-Eta:
  Fetching repository: https://github.com/tista500/Adapta ...
  Last updated 5 weeks ago. 
  Installing... 
  WARNING: Installation takes an especially long time due to rendering of all assets, please be patient! 
install-gnome-themes failed! 
```

Fedora 32, gnome 3.36.

**Comment by tliron** [comment]
What do see in the log? Any idea what is going wrong? `~/.themes/.install-gnome-themes.log`

**Comment by tliron** [comment]
I just committed another fix related to Inkscape (Inkscape keeps changing its CLI flags), hopefully this will help.

**Comment by vinliao** [comment]
Still fails. ~~And also I can't find the log on `~/.themes/` and `/tmp`~~

Here's the log
```
Detected GNOME 3.36, GTK 3.24.
Detected Fedora operating system.
Adapta, Adapta-Eta, Adapta-Nokto, Adapta-Nokto-Eta:
  Fetching repository: https://github.com/tista500/Adapta ...
Cloning into 'Adapta'...
  Last updated 5 weeks ago.
  Installing...
  WARNING: Installation takes an especially long time due to rendering of all assets, please be patient!
configure.ac:14: installing './install-sh'
configure.ac:14: installing './missing'
+ ./configure --enable-parallel --prefix=/tmp/install-gnome-themes/Adapta --disable-cinnamon --disable-xfce --disable-mate --disable-openbox --enable-chrome-legacy
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GDK_PIXBUF... no
configure: error: Package requirements (gdk-pixbuf-2.0 >= 2.32.2) were not met:

Package 'gdk-pixbuf-2.0', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GDK_PIXBUF_CFLAGS
and GDK_PIXBUF_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
install-gnome-themes failed!
```

**Comment by vinliao** [comment]
Silly me, I installed the needed deps and it works now. Thanks for the help @tliron.
